name: 'Pull Request action'

on:
  pull_request:
    branches: [ main ]
jobs:
  Build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install Node'
        uses: actions/setup-node@v6
        with:
          node-version: 18.19.1
      - name: 'Install angular'
        run: |
           npm i -g @angular/cli@19.2.18
           ng version
      - name: 'Build my-programs-mfe'
        run: |
          npm install
          ng build
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: my-programs-build-artifact
          path: .
  Test:
    name: 'Unit Testing'
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: 'Setup environement'
        uses: actions/setup-node@v6
        with:
          node-version: 18.19.1
      - name: 'Setup angular'
        run: |
          npm install -g @angular/cli@19.2.18
          ng version
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt update && sudo apt install yarn
          yarn --version
          rm -rf yarn.lock
      - name: 'Download Build artifacts'
        uses: actions/download-artifact@v5
        with:
           name: my-programs-build-artifact
      - name: 'Unit Testing'
        run: |
          yarn test
      - name: 'Linting'
        run: yarn lint





